-<template>
-    <article id="app">
-        <router-view></router-view>
-    </article>
-</template>
-
-<script>
-export default {
-    name: 'app'
-};
-</script>
-
-<style lang="less">
-    @import "./styles/common/common.less";
-</style>
